version: 2

models:
  - name: stg_generacion_real
    columns:
      - name: central_id
        tests:
          - not_null
      - name: timesatamp_local
        tests:
          - not_null
      - name: generacion_real_mw
        tests:
          - not_null
